name: Tests
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Dependencies
      run: npm i
    - name: Eslint
      run: npm run lint
    - name: Jest
      run: npm run test:ci
    - name: Jest
      run: npm run test:ci:report
    - name: Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run:
        curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN

  docker-build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t image:local -f ./Dockerfile .
      - run: docker run --rm image:local --help
